// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/database/objectbox/models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4116015513592481801),
      name: 'ChatMessage',
      lastPropertyId: const obx_int.IdUid(7, 6342858253352834301),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4482910682150416658),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3317828204513598000),
            name: 'userSupabaseId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1752091508111459656),
            name: 'message',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7672671001962769084),
            name: 'isUser',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8786075534898045507),
            name: 'response',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6290802186253961991),
            name: 'sourceTextbookIds',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6342858253352834301),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2757515627549073300),
      name: 'QuizResult',
      lastPropertyId: const obx_int.IdUid(9, 634110694115170085),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2801390201627132597),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7648819588022213474),
            name: 'userSupabaseId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6613167907554262495),
            name: 'subjectCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2973106427887244068),
            name: 'grade',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 485037056357113370),
            name: 'totalQuestions',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8495809005961554718),
            name: 'correctAnswers',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4176108749703686297),
            name: 'score',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5409248955520501806),
            name: 'durationMinutes',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 634110694115170085),
            name: 'completedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 4615717302247308991),
      name: 'Subject',
      lastPropertyId: const obx_int.IdUid(6, 1338485980178578817),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 59260056013627260),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1833842442573459678),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5262610002675671096),
            name: 'subjectCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5472966445020041969),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3073042317287282063),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1338485980178578817),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3974065955896488451),
      name: 'Textbook',
      lastPropertyId: const obx_int.IdUid(10, 3234768393229631016),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5378568322990998895),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5124895285015973916),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 122438309647019096),
            name: 'subjectCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7830985147136995787),
            name: 'grade',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5320179184752121950),
            name: 'filePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3956186200072271132),
            name: 'fileSize',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7118377723743156633),
            name: 'pageCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4151573621769053681),
            name: 'isProcessed',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6888053553618934798),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 3234768393229631016),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 5787175614198442148),
      name: 'TextbookChunk',
      lastPropertyId: const obx_int.IdUid(6, 8538558964345464028),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 293273695227751420),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2268232807428644018),
            name: 'chunkText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9101410919043306784),
            name: 'chunkIndex',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1665269981442882541),
            name: 'embedding',
            type: 29,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1652204372709998729),
            name: 'textbookId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 2265054185031022173),
            relationTarget: 'Textbook'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8538558964345464028),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 4896875631737941585),
      name: 'UserProfile',
      lastPropertyId: const obx_int.IdUid(9, 1851727771280845090),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 385937721683152452),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3840956014936952128),
            name: 'supabaseUserId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 598765609343191389),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4161644889273442381),
            name: 'firstName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8357494253113383448),
            name: 'lastName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5586971783562003160),
            name: 'grade',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4358583954377305047),
            name: 'isPremium',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1549279959690894484),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1851727771280845090),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 8550711164787482405),
      name: 'UserProgress',
      lastPropertyId: const obx_int.IdUid(10, 2560223921533167051),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4296051907309180915),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1190627659309387437),
            name: 'userSupabaseId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4147860876999170879),
            name: 'subjectCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4965580476583732192),
            name: 'grade',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1952224630239009047),
            name: 'completedPages',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7355192246275083283),
            name: 'totalPages',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4470567368560741033),
            name: 'progressPercentage',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6034187445677365297),
            name: 'lastAccessedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1167263387010706323),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 2560223921533167051),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 8550711164787482405),
      lastIndexId: const obx_int.IdUid(1, 2265054185031022173),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessage: obx_int.EntityDefinition<ChatMessage>(
        model: _entities[0],
        toOneRelations: (ChatMessage object) => [],
        toManyRelations: (ChatMessage object) => {},
        getId: (ChatMessage object) => object.id,
        setId: (ChatMessage object, int id) {
          object.id = id;
        },
        objectToFB: (ChatMessage object, fb.Builder fbb) {
          final userSupabaseIdOffset = fbb.writeString(object.userSupabaseId);
          final messageOffset = fbb.writeString(object.message);
          final responseOffset = fbb.writeString(object.response);
          final sourceTextbookIdsOffset = fbb.writeList(object.sourceTextbookIds
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userSupabaseIdOffset);
          fbb.addOffset(2, messageOffset);
          fbb.addBool(3, object.isUser);
          fbb.addOffset(4, responseOffset);
          fbb.addOffset(5, sourceTextbookIdsOffset);
          fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final userSupabaseIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final messageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final isUserParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final responseParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final sourceTextbookIdsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 14, []);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final object = ChatMessage(
              userSupabaseId: userSupabaseIdParam,
              message: messageParam,
              isUser: isUserParam,
              response: responseParam,
              sourceTextbookIds: sourceTextbookIdsParam,
              createdAt: createdAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    QuizResult: obx_int.EntityDefinition<QuizResult>(
        model: _entities[1],
        toOneRelations: (QuizResult object) => [],
        toManyRelations: (QuizResult object) => {},
        getId: (QuizResult object) => object.id,
        setId: (QuizResult object, int id) {
          object.id = id;
        },
        objectToFB: (QuizResult object, fb.Builder fbb) {
          final userSupabaseIdOffset = fbb.writeString(object.userSupabaseId);
          final subjectCodeOffset = fbb.writeString(object.subjectCode);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userSupabaseIdOffset);
          fbb.addOffset(2, subjectCodeOffset);
          fbb.addInt64(3, object.grade);
          fbb.addInt64(4, object.totalQuestions);
          fbb.addInt64(5, object.correctAnswers);
          fbb.addFloat64(6, object.score);
          fbb.addInt64(7, object.durationMinutes);
          fbb.addInt64(8, object.completedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final userSupabaseIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final subjectCodeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final gradeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final totalQuestionsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final correctAnswersParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final scoreParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final durationMinutesParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final completedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final object = QuizResult(
              userSupabaseId: userSupabaseIdParam,
              subjectCode: subjectCodeParam,
              grade: gradeParam,
              totalQuestions: totalQuestionsParam,
              correctAnswers: correctAnswersParam,
              score: scoreParam,
              durationMinutes: durationMinutesParam,
              completedAt: completedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Subject: obx_int.EntityDefinition<Subject>(
        model: _entities[2],
        toOneRelations: (Subject object) => [],
        toManyRelations: (Subject object) => {},
        getId: (Subject object) => object.id,
        setId: (Subject object, int id) {
          object.id = id;
        },
        objectToFB: (Subject object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final subjectCodeOffset = fbb.writeString(object.subjectCode);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, subjectCodeOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final subjectCodeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final object = Subject(
              name: nameParam,
              subjectCode: subjectCodeParam,
              description: descriptionParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Textbook: obx_int.EntityDefinition<Textbook>(
        model: _entities[3],
        toOneRelations: (Textbook object) => [],
        toManyRelations: (Textbook object) => {},
        getId: (Textbook object) => object.id,
        setId: (Textbook object, int id) {
          object.id = id;
        },
        objectToFB: (Textbook object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final subjectCodeOffset = fbb.writeString(object.subjectCode);
          final filePathOffset = fbb.writeString(object.filePath);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, subjectCodeOffset);
          fbb.addInt64(3, object.grade);
          fbb.addOffset(4, filePathOffset);
          fbb.addInt64(5, object.fileSize);
          fbb.addInt64(6, object.pageCount);
          fbb.addBool(7, object.isProcessed);
          fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final subjectCodeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final gradeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final filePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final fileSizeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final pageCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final isProcessedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 18, false);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));
          final object = Textbook(
              title: titleParam,
              subjectCode: subjectCodeParam,
              grade: gradeParam,
              filePath: filePathParam,
              fileSize: fileSizeParam,
              pageCount: pageCountParam,
              isProcessed: isProcessedParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TextbookChunk: obx_int.EntityDefinition<TextbookChunk>(
        model: _entities[4],
        toOneRelations: (TextbookChunk object) => [object.textbook],
        toManyRelations: (TextbookChunk object) => {},
        getId: (TextbookChunk object) => object.id,
        setId: (TextbookChunk object, int id) {
          object.id = id;
        },
        objectToFB: (TextbookChunk object, fb.Builder fbb) {
          final chunkTextOffset = fbb.writeString(object.chunkText);
          final embeddingOffset = fbb.writeListFloat64(object.embedding);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, chunkTextOffset);
          fbb.addInt64(2, object.chunkIndex);
          fbb.addOffset(3, embeddingOffset);
          fbb.addInt64(4, object.textbook.targetId);
          fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final chunkTextParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final chunkIndexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final embeddingParam =
              const fb.ListReader<double>(fb.Float64Reader(), lazy: false)
                  .vTableGet(buffer, rootOffset, 10, []);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final object = TextbookChunk(
              chunkText: chunkTextParam,
              chunkIndex: chunkIndexParam,
              embedding: embeddingParam,
              createdAt: createdAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.textbook.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.textbook.attach(store);
          return object;
        }),
    UserProfile: obx_int.EntityDefinition<UserProfile>(
        model: _entities[5],
        toOneRelations: (UserProfile object) => [],
        toManyRelations: (UserProfile object) => {},
        getId: (UserProfile object) => object.id,
        setId: (UserProfile object, int id) {
          object.id = id;
        },
        objectToFB: (UserProfile object, fb.Builder fbb) {
          final supabaseUserIdOffset = fbb.writeString(object.supabaseUserId);
          final emailOffset = fbb.writeString(object.email);
          final firstNameOffset = fbb.writeString(object.firstName);
          final lastNameOffset = fbb.writeString(object.lastName);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, supabaseUserIdOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, firstNameOffset);
          fbb.addOffset(4, lastNameOffset);
          fbb.addInt64(5, object.grade);
          fbb.addBool(6, object.isPremium);
          fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final supabaseUserIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final firstNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final lastNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final gradeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final isPremiumParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final object = UserProfile(
              supabaseUserId: supabaseUserIdParam,
              email: emailParam,
              firstName: firstNameParam,
              lastName: lastNameParam,
              grade: gradeParam,
              isPremium: isPremiumParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    UserProgress: obx_int.EntityDefinition<UserProgress>(
        model: _entities[6],
        toOneRelations: (UserProgress object) => [],
        toManyRelations: (UserProgress object) => {},
        getId: (UserProgress object) => object.id,
        setId: (UserProgress object, int id) {
          object.id = id;
        },
        objectToFB: (UserProgress object, fb.Builder fbb) {
          final userSupabaseIdOffset = fbb.writeString(object.userSupabaseId);
          final subjectCodeOffset = fbb.writeString(object.subjectCode);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userSupabaseIdOffset);
          fbb.addOffset(2, subjectCodeOffset);
          fbb.addInt64(3, object.grade);
          fbb.addInt64(4, object.completedPages);
          fbb.addInt64(5, object.totalPages);
          fbb.addFloat64(6, object.progressPercentage);
          fbb.addInt64(7, object.lastAccessedAt.millisecondsSinceEpoch);
          fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final userSupabaseIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final subjectCodeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final gradeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final completedPagesParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final totalPagesParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final progressPercentageParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final lastAccessedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));
          final object = UserProgress(
              userSupabaseId: userSupabaseIdParam,
              subjectCode: subjectCodeParam,
              grade: gradeParam,
              completedPages: completedPagesParam,
              totalPages: totalPagesParam,
              progressPercentage: progressPercentageParam,
              lastAccessedAt: lastAccessedAtParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessage] entity fields to define ObjectBox queries.
class ChatMessage_ {
  /// see [ChatMessage.id]
  static final id =
      obx.QueryIntegerProperty<ChatMessage>(_entities[0].properties[0]);

  /// see [ChatMessage.userSupabaseId]
  static final userSupabaseId =
      obx.QueryStringProperty<ChatMessage>(_entities[0].properties[1]);

  /// see [ChatMessage.message]
  static final message =
      obx.QueryStringProperty<ChatMessage>(_entities[0].properties[2]);

  /// see [ChatMessage.isUser]
  static final isUser =
      obx.QueryBooleanProperty<ChatMessage>(_entities[0].properties[3]);

  /// see [ChatMessage.response]
  static final response =
      obx.QueryStringProperty<ChatMessage>(_entities[0].properties[4]);

  /// see [ChatMessage.sourceTextbookIds]
  static final sourceTextbookIds =
      obx.QueryStringVectorProperty<ChatMessage>(_entities[0].properties[5]);

  /// see [ChatMessage.createdAt]
  static final createdAt =
      obx.QueryDateProperty<ChatMessage>(_entities[0].properties[6]);
}

/// [QuizResult] entity fields to define ObjectBox queries.
class QuizResult_ {
  /// see [QuizResult.id]
  static final id =
      obx.QueryIntegerProperty<QuizResult>(_entities[1].properties[0]);

  /// see [QuizResult.userSupabaseId]
  static final userSupabaseId =
      obx.QueryStringProperty<QuizResult>(_entities[1].properties[1]);

  /// see [QuizResult.subjectCode]
  static final subjectCode =
      obx.QueryStringProperty<QuizResult>(_entities[1].properties[2]);

  /// see [QuizResult.grade]
  static final grade =
      obx.QueryIntegerProperty<QuizResult>(_entities[1].properties[3]);

  /// see [QuizResult.totalQuestions]
  static final totalQuestions =
      obx.QueryIntegerProperty<QuizResult>(_entities[1].properties[4]);

  /// see [QuizResult.correctAnswers]
  static final correctAnswers =
      obx.QueryIntegerProperty<QuizResult>(_entities[1].properties[5]);

  /// see [QuizResult.score]
  static final score =
      obx.QueryDoubleProperty<QuizResult>(_entities[1].properties[6]);

  /// see [QuizResult.durationMinutes]
  static final durationMinutes =
      obx.QueryIntegerProperty<QuizResult>(_entities[1].properties[7]);

  /// see [QuizResult.completedAt]
  static final completedAt =
      obx.QueryDateProperty<QuizResult>(_entities[1].properties[8]);
}

/// [Subject] entity fields to define ObjectBox queries.
class Subject_ {
  /// see [Subject.id]
  static final id =
      obx.QueryIntegerProperty<Subject>(_entities[2].properties[0]);

  /// see [Subject.name]
  static final name =
      obx.QueryStringProperty<Subject>(_entities[2].properties[1]);

  /// see [Subject.subjectCode]
  static final subjectCode =
      obx.QueryStringProperty<Subject>(_entities[2].properties[2]);

  /// see [Subject.description]
  static final description =
      obx.QueryStringProperty<Subject>(_entities[2].properties[3]);

  /// see [Subject.createdAt]
  static final createdAt =
      obx.QueryDateProperty<Subject>(_entities[2].properties[4]);

  /// see [Subject.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<Subject>(_entities[2].properties[5]);
}

/// [Textbook] entity fields to define ObjectBox queries.
class Textbook_ {
  /// see [Textbook.id]
  static final id =
      obx.QueryIntegerProperty<Textbook>(_entities[3].properties[0]);

  /// see [Textbook.title]
  static final title =
      obx.QueryStringProperty<Textbook>(_entities[3].properties[1]);

  /// see [Textbook.subjectCode]
  static final subjectCode =
      obx.QueryStringProperty<Textbook>(_entities[3].properties[2]);

  /// see [Textbook.grade]
  static final grade =
      obx.QueryIntegerProperty<Textbook>(_entities[3].properties[3]);

  /// see [Textbook.filePath]
  static final filePath =
      obx.QueryStringProperty<Textbook>(_entities[3].properties[4]);

  /// see [Textbook.fileSize]
  static final fileSize =
      obx.QueryIntegerProperty<Textbook>(_entities[3].properties[5]);

  /// see [Textbook.pageCount]
  static final pageCount =
      obx.QueryIntegerProperty<Textbook>(_entities[3].properties[6]);

  /// see [Textbook.isProcessed]
  static final isProcessed =
      obx.QueryBooleanProperty<Textbook>(_entities[3].properties[7]);

  /// see [Textbook.createdAt]
  static final createdAt =
      obx.QueryDateProperty<Textbook>(_entities[3].properties[8]);

  /// see [Textbook.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<Textbook>(_entities[3].properties[9]);
}

/// [TextbookChunk] entity fields to define ObjectBox queries.
class TextbookChunk_ {
  /// see [TextbookChunk.id]
  static final id =
      obx.QueryIntegerProperty<TextbookChunk>(_entities[4].properties[0]);

  /// see [TextbookChunk.chunkText]
  static final chunkText =
      obx.QueryStringProperty<TextbookChunk>(_entities[4].properties[1]);

  /// see [TextbookChunk.chunkIndex]
  static final chunkIndex =
      obx.QueryIntegerProperty<TextbookChunk>(_entities[4].properties[2]);

  /// see [TextbookChunk.embedding]
  static final embedding =
      obx.QueryDoubleVectorProperty<TextbookChunk>(_entities[4].properties[3]);

  /// see [TextbookChunk.textbook]
  static final textbook = obx.QueryRelationToOne<TextbookChunk, Textbook>(
      _entities[4].properties[4]);

  /// see [TextbookChunk.createdAt]
  static final createdAt =
      obx.QueryDateProperty<TextbookChunk>(_entities[4].properties[5]);
}

/// [UserProfile] entity fields to define ObjectBox queries.
class UserProfile_ {
  /// see [UserProfile.id]
  static final id =
      obx.QueryIntegerProperty<UserProfile>(_entities[5].properties[0]);

  /// see [UserProfile.supabaseUserId]
  static final supabaseUserId =
      obx.QueryStringProperty<UserProfile>(_entities[5].properties[1]);

  /// see [UserProfile.email]
  static final email =
      obx.QueryStringProperty<UserProfile>(_entities[5].properties[2]);

  /// see [UserProfile.firstName]
  static final firstName =
      obx.QueryStringProperty<UserProfile>(_entities[5].properties[3]);

  /// see [UserProfile.lastName]
  static final lastName =
      obx.QueryStringProperty<UserProfile>(_entities[5].properties[4]);

  /// see [UserProfile.grade]
  static final grade =
      obx.QueryIntegerProperty<UserProfile>(_entities[5].properties[5]);

  /// see [UserProfile.isPremium]
  static final isPremium =
      obx.QueryBooleanProperty<UserProfile>(_entities[5].properties[6]);

  /// see [UserProfile.createdAt]
  static final createdAt =
      obx.QueryDateProperty<UserProfile>(_entities[5].properties[7]);

  /// see [UserProfile.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<UserProfile>(_entities[5].properties[8]);
}

/// [UserProgress] entity fields to define ObjectBox queries.
class UserProgress_ {
  /// see [UserProgress.id]
  static final id =
      obx.QueryIntegerProperty<UserProgress>(_entities[6].properties[0]);

  /// see [UserProgress.userSupabaseId]
  static final userSupabaseId =
      obx.QueryStringProperty<UserProgress>(_entities[6].properties[1]);

  /// see [UserProgress.subjectCode]
  static final subjectCode =
      obx.QueryStringProperty<UserProgress>(_entities[6].properties[2]);

  /// see [UserProgress.grade]
  static final grade =
      obx.QueryIntegerProperty<UserProgress>(_entities[6].properties[3]);

  /// see [UserProgress.completedPages]
  static final completedPages =
      obx.QueryIntegerProperty<UserProgress>(_entities[6].properties[4]);

  /// see [UserProgress.totalPages]
  static final totalPages =
      obx.QueryIntegerProperty<UserProgress>(_entities[6].properties[5]);

  /// see [UserProgress.progressPercentage]
  static final progressPercentage =
      obx.QueryDoubleProperty<UserProgress>(_entities[6].properties[6]);

  /// see [UserProgress.lastAccessedAt]
  static final lastAccessedAt =
      obx.QueryDateProperty<UserProgress>(_entities[6].properties[7]);

  /// see [UserProgress.createdAt]
  static final createdAt =
      obx.QueryDateProperty<UserProgress>(_entities[6].properties[8]);

  /// see [UserProgress.updatedAt]
  static final updatedAt =
      obx.QueryDateProperty<UserProgress>(_entities[6].properties[9]);
}
